### ISSUE TITLE
Instead of overriding files, change file names.

### ISSUE THREAD

**Issue by mmzeynalli** [aminalaee/fastapi-storages#30]
Currently, if I upload two DIFFERENT images with the same name, one overrides another. In order to avoid this, it would be better to change filename to `filename_1`, `filename_2` before writing to folder.

**Comment by aminalaee** [comment]
Hey,
thanks for the issue and the fix.

One improvement I can think of is that we can add a flag like `OVERWRITE_EXISTING_FILE = True` which should be supported by both FileSystemStorage and S3Storage backends.
The reason is that I think this should be controlled, as some people might want to have this feature and it will be a problem.

**Comment by aminalaee** [comment]
Thanks @mmzeynalli 
Closed in https://github.com/aminalaee/fastapi-storages/pull/31
